[package]
name = "fuzz_with_emus"
version = "0.1.0"
authors = ["hacmao"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
